-- V3__seed_words.sql
-- 600 English-Russian vocabulary words, 100 per level (A1-C2)

-- ============================================================
-- A1 — Beginner (100 words)
-- ============================================================
INSERT INTO words (english, russian, level, category) VALUES
('apple','яблоко','A1','food'),
('bread','хлеб','A1','food'),
('butter','масло','A1','food'),
('cake','торт','A1','food'),
('cheese','сыр','A1','food'),
('chicken','курица','A1','food'),
('coffee','кофе','A1','food'),
('egg','яйцо','A1','food'),
('fish','рыба','A1','food'),
('milk','молоко','A1','food'),
('bus','автобус','A1','travel'),
('car','машина','A1','travel'),
('city','город','A1','travel'),
('map','карта','A1','travel'),
('road','дорога','A1','travel'),
('station','станция','A1','travel'),
('ticket','билет','A1','travel'),
('train','поезд','A1','travel'),
('bed','кровать','A1','home'),
('chair','стул','A1','home'),
('door','дверь','A1','home'),
('floor','пол','A1','home'),
('house','дом','A1','home'),
('kitchen','кухня','A1','home'),
('lamp','лампа','A1','home'),
('table','стол','A1','home'),
('wall','стена','A1','home'),
('window','окно','A1','home'),
('arm','рука','A1','health'),
('doctor','врач','A1','health'),
('eye','глаз','A1','health'),
('hand','кисть руки','A1','health'),
('head','голова','A1','health'),
('hospital','больница','A1','health'),
('leg','нога','A1','health'),
('nose','нос','A1','health'),
('book','книга','A1','education'),
('class','класс','A1','education'),
('pen','ручка','A1','education'),
('pencil','карандаш','A1','education'),
('school','школа','A1','education'),
('student','студент','A1','education'),
('teacher','учитель','A1','education'),
('cat','кошка','A1','nature'),
('dog','собака','A1','nature'),
('flower','цветок','A1','nature'),
('moon','луна','A1','nature'),
('rain','дождь','A1','nature'),
('sky','небо','A1','nature'),
('snow','снег','A1','nature'),
('sun','солнце','A1','nature'),
('tree','дерево','A1','nature'),
('water','вода','A1','nature'),
('bag','сумка','A1','shopping'),
('money','деньги','A1','shopping'),
('price','цена','A1','shopping'),
('shop','магазин','A1','shopping'),
('shirt','рубашка','A1','shopping'),
('shoes','туфли','A1','shopping'),
('film','фильм','A1','entertainment'),
('game','игра','A1','entertainment'),
('music','музыка','A1','entertainment'),
('photo','фото','A1','entertainment'),
('sport','спорт','A1','entertainment'),
('computer','компьютер','A1','technology'),
('phone','телефон','A1','technology'),
('television','телевизор','A1','technology'),
('job','работа','A1','work'),
('office','офис','A1','work'),
('baby','ребёнок','A1',NULL),
('big','большой','A1',NULL),
('boy','мальчик','A1',NULL),
('brother','брат','A1',NULL),
('color','цвет','A1',NULL),
('day','день','A1',NULL),
('family','семья','A1',NULL),
('father','отец','A1',NULL),
('friend','друг','A1',NULL),
('girl','девочка','A1',NULL),
('good','хороший','A1',NULL),
('hello','привет','A1',NULL),
('home','дом/домой','A1',NULL),
('man','мужчина','A1',NULL),
('mother','мать','A1',NULL),
('name','имя','A1',NULL),
('new','новый','A1',NULL),
('no','нет','A1',NULL),
('number','номер','A1',NULL),
('old','старый','A1',NULL),
('one','один','A1',NULL),
('sister','сестра','A1',NULL),
('small','маленький','A1',NULL),
('time','время','A1',NULL),
('today','сегодня','A1',NULL),
('woman','женщина','A1',NULL),
('word','слово','A1',NULL),
('year','год','A1',NULL),
('yes','да','A1',NULL),
('zero','ноль','A1',NULL)
ON CONFLICT (english) DO NOTHING;

-- ============================================================
-- A2 — Elementary (100 words)
-- ============================================================
INSERT INTO words (english, russian, level, category) VALUES
('banana','банан','A2','food'),
('breakfast','завтрак','A2','food'),
('cucumber','огурец','A2','food'),
('dinner','ужин','A2','food'),
('fruit','фрукт','A2','food'),
('ice cream','мороженое','A2','food'),
('juice','сок','A2','food'),
('lunch','обед','A2','food'),
('meat','мясо','A2','food'),
('soup','суп','A2','food'),
('airport','аэропорт','A2','travel'),
('bicycle','велосипед','A2','travel'),
('border','граница','A2','travel'),
('bus stop','автобусная остановка','A2','travel'),
('country','страна','A2','travel'),
('hotel','гостиница','A2','travel'),
('luggage','багаж','A2','travel'),
('passport','паспорт','A2','travel'),
('taxi','такси','A2','travel'),
('trip','поездка','A2','travel'),
('bathroom','ванная','A2','home'),
('bedroom','спальня','A2','home'),
('cupboard','шкаф','A2','home'),
('garden','сад','A2','home'),
('living room','гостиная','A2','home'),
('neighbour','сосед','A2','home'),
('roof','крыша','A2','home'),
('sofa','диван','A2','home'),
('cold','простуда','A2','health'),
('dentist','стоматолог','A2','health'),
('fever','температура','A2','health'),
('medicine','лекарство','A2','health'),
('nurse','медсестра','A2','health'),
('pain','боль','A2','health'),
('pharmacy','аптека','A2','health'),
('dictionary','словарь','A2','education'),
('exam','экзамен','A2','education'),
('homework','домашнее задание','A2','education'),
('lesson','урок','A2','education'),
('library','библиотека','A2','education'),
('notebook','тетрадь','A2','education'),
('university','университет','A2','education'),
('beach','пляж','A2','nature'),
('bird','птица','A2','nature'),
('cloud','облако','A2','nature'),
('forest','лес','A2','nature'),
('horse','лошадь','A2','nature'),
('island','остров','A2','nature'),
('lake','озеро','A2','nature'),
('mountain','гора','A2','nature'),
('river','река','A2','nature'),
('season','сезон','A2','nature'),
('cheap','дешёвый','A2','shopping'),
('expensive','дорогой','A2','shopping'),
('market','рынок','A2','shopping'),
('receipt','чек','A2','shopping'),
('size','размер','A2','shopping'),
('supermarket','супермаркет','A2','shopping'),
('concert','концерт','A2','entertainment'),
('hobby','хобби','A2','entertainment'),
('magazine','журнал','A2','entertainment'),
('party','вечеринка','A2','entertainment'),
('restaurant','ресторан','A2','entertainment'),
('theatre','театр','A2','entertainment'),
('camera','фотоаппарат','A2','technology'),
('internet','интернет','A2','technology'),
('message','сообщение','A2','technology'),
('printer','принтер','A2','technology'),
('radio','радио','A2','technology'),
('boss','начальник','A2','work'),
('company','компания','A2','work'),
('meeting','встреча','A2','work'),
('salary','зарплата','A2','work'),
('secretary','секретарь','A2','work'),
('address','адрес','A2',NULL),
('age','возраст','A2',NULL),
('answer','ответ','A2',NULL),
('beautiful','красивый','A2',NULL),
('birthday','день рождения','A2',NULL),
('colour','цвет (брит.)','A2',NULL),
('different','другой','A2',NULL),
('difficult','трудный','A2',NULL),
('happy','счастливый','A2',NULL),
('holiday','праздник','A2',NULL),
('important','важный','A2',NULL),
('language','язык','A2',NULL),
('letter','письмо','A2',NULL),
('quickly','быстро','A2',NULL),
('question','вопрос','A2',NULL),
('ready','готовый','A2',NULL),
('slow','медленный','A2',NULL),
('sometimes','иногда','A2',NULL),
('together','вместе','A2',NULL),
('weather','погода','A2',NULL)
ON CONFLICT (english) DO NOTHING;

-- ============================================================
-- B1 — Intermediate (100 words)
-- ============================================================
INSERT INTO words (english, russian, level, category) VALUES
('cuisine','кухня (нац.)','B1','food'),
('delicious','вкусный','B1','food'),
('ingredient','ингредиент','B1','food'),
('nutrition','питание','B1','food'),
('recipe','рецепт','B1','food'),
('snack','перекус','B1','food'),
('vegetarian','вегетарианский','B1','food'),
('accommodation','жильё','B1','travel'),
('adventure','приключение','B1','travel'),
('attraction','достопримечательность','B1','travel'),
('customs','таможня','B1','travel'),
('destination','место назначения','B1','travel'),
('excursion','экскурсия','B1','travel'),
('reservation','бронирование','B1','travel'),
('tourist','турист','B1','travel'),
('visa','виза','B1','travel'),
('appliance','бытовой прибор','B1','home'),
('balcony','балкон','B1','home'),
('basement','подвал','B1','home'),
('furniture','мебель','B1','home'),
('landlord','арендодатель','B1','home'),
('mortgage','ипотека','B1','home'),
('renovation','ремонт','B1','home'),
('allergy','аллергия','B1','health'),
('ambulance','скорая помощь','B1','health'),
('appointment','приём (врача)','B1','health'),
('diet','диета','B1','health'),
('exercise','физические упражнения','B1','health'),
('operation','операция','B1','health'),
('prescription','рецепт (мед.)','B1','health'),
('symptom','симптом','B1','health'),
('treatment','лечение','B1','health'),
('assignment','задание','B1','education'),
('certificate','сертификат','B1','education'),
('curriculum','учебная программа','B1','education'),
('degree','учёная степень','B1','education'),
('essay','эссе','B1','education'),
('graduate','выпускник','B1','education'),
('scholarship','стипендия','B1','education'),
('seminar','семинар','B1','education'),
('climate','климат','B1','nature'),
('earthquake','землетрясение','B1','nature'),
('ecosystem','экосистема','B1','nature'),
('endangered','под угрозой исчезновения','B1','nature'),
('environment','окружающая среда','B1','nature'),
('hurricane','ураган','B1','nature'),
('pollution','загрязнение','B1','nature'),
('wildlife','дикая природа','B1','nature'),
('bargain','выгодная покупка','B1','shopping'),
('brand','бренд','B1','shopping'),
('consumer','потребитель','B1','shopping'),
('discount','скидка','B1','shopping'),
('guarantee','гарантия','B1','shopping'),
('refund','возврат денег','B1','shopping'),
('warranty','гарантийный срок','B1','shopping'),
('animation','анимация','B1','entertainment'),
('audience','публика','B1','entertainment'),
('celebrity','знаменитость','B1','entertainment'),
('documentary','документальный фильм','B1','entertainment'),
('festival','фестиваль','B1','entertainment'),
('performance','выступление','B1','entertainment'),
('application','приложение','B1','technology'),
('database','база данных','B1','technology'),
('download','скачивание','B1','technology'),
('email','электронная почта','B1','technology'),
('hardware','оборудование','B1','technology'),
('network','сеть','B1','technology'),
('software','программное обеспечение','B1','technology'),
('upload','загрузка','B1','technology'),
('career','карьера','B1','work'),
('colleague','коллега','B1','work'),
('deadline','срок','B1','work'),
('employee','сотрудник','B1','work'),
('employer','работодатель','B1','work'),
('interview','интервью','B1','work'),
('promotion','повышение','B1','work'),
('achieve','достичь','B1',NULL),
('advantage','преимущество','B1',NULL),
('belief','убеждение','B1',NULL),
('challenge','испытание','B1',NULL),
('democracy','демократия','B1',NULL),
('describe','описывать','B1',NULL),
('efficient','эффективный','B1',NULL),
('experience','опыт','B1',NULL),
('furthermore','более того','B1',NULL),
('however','однако','B1',NULL),
('influence','влияние','B1',NULL),
('meanwhile','тем временем','B1',NULL),
('opinion','мнение','B1',NULL),
('opportunity','возможность','B1',NULL),
('recently','недавно','B1',NULL),
('responsible','ответственный','B1',NULL),
('significant','значительный','B1',NULL),
('society','общество','B1',NULL),
('therefore','следовательно','B1',NULL),
('tradition','традиция','B1',NULL)
ON CONFLICT (english) DO NOTHING;

-- ============================================================
-- B2 — Upper-Intermediate (100 words)
-- ============================================================
INSERT INTO words (english, russian, level, category) VALUES
('appetizer','закуска','B2','food'),
('culinary','кулинарный','B2','food'),
('gourmet','гурман','B2','food'),
('marinade','маринад','B2','food'),
('palate','вкусовые ощущения','B2','food'),
('sustenance','пропитание','B2','food'),
('commute','ежедневные поездки','B2','travel'),
('cosmopolitan','космополитичный','B2','travel'),
('emigrate','эмигрировать','B2','travel'),
('itinerary','маршрут','B2','travel'),
('nomadic','кочевой','B2','travel'),
('pilgrimage','паломничество','B2','travel'),
('traverse','пересекать','B2','travel'),
('architect','архитектор','B2','home'),
('demolish','сносить','B2','home'),
('dwelling','жилище','B2','home'),
('estate','поместье','B2','home'),
('facade','фасад','B2','home'),
('infrastructure','инфраструктура','B2','home'),
('tenancy','аренда','B2','home'),
('chronic','хронический','B2','health'),
('diagnose','диагностировать','B2','health'),
('immunity','иммунитет','B2','health'),
('insomnia','бессонница','B2','health'),
('metabolism','метаболизм','B2','health'),
('rehabilitation','реабилитация','B2','health'),
('syndrome','синдром','B2','health'),
('therapy','терапия','B2','health'),
('academia','академическая среда','B2','education'),
('accreditation','аккредитация','B2','education'),
('dissertation','диссертация','B2','education'),
('faculty','факультет','B2','education'),
('pedagogy','педагогика','B2','education'),
('thesis','дипломная работа','B2','education'),
('tuition','обучение (плата)','B2','education'),
('biodiversity','биоразнообразие','B2','nature'),
('deforestation','вырубка лесов','B2','nature'),
('drought','засуха','B2','nature'),
('erosion','эрозия','B2','nature'),
('fossil','ископаемое','B2','nature'),
('glacier','ледник','B2','nature'),
('photosynthesis','фотосинтез','B2','nature'),
('precipitation','осадки','B2','nature'),
('acquisition','приобретение','B2','shopping'),
('counterfeit','поддельный','B2','shopping'),
('depreciation','обесценивание','B2','shopping'),
('entrepreneur','предприниматель','B2','shopping'),
('fluctuation','колебание','B2','shopping'),
('inflation','инфляция','B2','shopping'),
('choreography','хореография','B2','entertainment'),
('cinematography','кинематография','B2','entertainment'),
('improvisation','импровизация','B2','entertainment'),
('narrative','повествование','B2','entertainment'),
('satirical','сатирический','B2','entertainment'),
('symphony','симфония','B2','entertainment'),
('algorithm','алгоритм','B2','technology'),
('automation','автоматизация','B2','technology'),
('bandwidth','пропускная способность','B2','technology'),
('cybersecurity','кибербезопасность','B2','technology'),
('encryption','шифрование','B2','technology'),
('interface','интерфейс','B2','technology'),
('prototype','прототип','B2','technology'),
('bureaucracy','бюрократия','B2','work'),
('collaboration','сотрудничество','B2','work'),
('compensation','компенсация','B2','work'),
('endeavor','усилие','B2','work'),
('initiative','инициатива','B2','work'),
('negotiate','вести переговоры','B2','work'),
('accountability','подотчётность','B2',NULL),
('ambiguous','неоднозначный','B2',NULL),
('assumption','предположение','B2',NULL),
('coherent','связный','B2',NULL),
('consequence','последствие','B2',NULL),
('contradict','противоречить','B2',NULL),
('criterion','критерий','B2',NULL),
('dominant','доминирующий','B2',NULL),
('elaborate','разрабатывать','B2',NULL),
('emphasis','акцент','B2',NULL),
('fluctuate','колебаться','B2',NULL),
('fundamental','фундаментальный','B2',NULL),
('hypothesis','гипотеза','B2',NULL),
('implement','внедрять','B2',NULL),
('inherent','присущий','B2',NULL),
('legitimate','законный','B2',NULL),
('methodology','методология','B2',NULL),
('phenomenon','феномен','B2',NULL),
('reluctant','неохотный','B2',NULL),
('sophisticated','изощрённый','B2',NULL),
('subsequent','последующий','B2',NULL),
('contemplate','обдумывать','B2',NULL),
('inevitable','неизбежный','B2',NULL),
('undermine','подрывать','B2',NULL),
('achieve','достигать','B2',NULL),
('ambivalent','амбивалентный','B2',NULL),
('unprecedented','беспрецедентный','B2',NULL),
('rhetoric','риторика','B2',NULL),
('scrutinize','изучать','B2',NULL),
('speculate','рассуждать','B2',NULL),
('sustain','поддерживать','B2',NULL),
('transition','переход','B2',NULL)
ON CONFLICT (english) DO NOTHING;

-- ============================================================
-- C1 — Advanced (100 words)
-- ============================================================
INSERT INTO words (english, russian, level, category) VALUES
('gastronomy','гастрономия','C1','food'),
('delectable','восхитительный','C1','food'),
('concoction','смесь','C1','food'),
('infusion','настой','C1','food'),
('delicacy','деликатес','C1','food'),
('ascetic','аскетичный','C1','food'),
('clandestine','тайный','C1','travel'),
('diaspora','диаспора','C1','travel'),
('expatriate','эмигрант','C1','travel'),
('odyssey','одиссея','C1','travel'),
('sojourn','временное пребывание','C1','travel'),
('wayfarer','странник','C1','travel'),
('antiquated','устаревший','C1','home'),
('commodious','просторный','C1','home'),
('dilapidated','ветхий','C1','home'),
('domicile','местожительство','C1','home'),
('palatial','роскошный','C1','home'),
('ramshackle','развалившийся','C1','home'),
('convalescent','выздоравливающий','C1','health'),
('debilitating','изнурительный','C1','health'),
('epidemiology','эпидемиология','C1','health'),
('hypochondria','ипохондрия','C1','health'),
('malignant','злокачественный','C1','health'),
('pathogen','патоген','C1','health'),
('prognosis','прогноз (мед.)','C1','health'),
('didactic','дидактический','C1','education'),
('erudite','эрудированный','C1','education'),
('pedagogue','педагог','C1','education'),
('postulate','постулат','C1','education'),
('scholastic','схоластический','C1','education'),
('anthropogenic','антропогенный','C1','nature'),
('biome','биом','C1','nature'),
('cataclysm','катаклизм','C1','nature'),
('metamorphosis','метаморфоз','C1','nature'),
('symbiosis','симбиоз','C1','nature'),
('tectonic','тектонический','C1','nature'),
('conspicuous','заметный','C1','shopping'),
('exorbitant','непомерный','C1','shopping'),
('fiscal','фискальный','C1','shopping'),
('monetise','монетизировать','C1','shopping'),
('proliferate','распространяться','C1','shopping'),
('avant-garde','авангард','C1','entertainment'),
('catharsis','катарсис','C1','entertainment'),
('denouement','развязка','C1','entertainment'),
('juxtapose','сопоставлять','C1','entertainment'),
('soliloquy','монолог','C1','entertainment'),
('tragicomedy','трагикомедия','C1','entertainment'),
('biometric','биометрический','C1','technology'),
('decentralised','децентрализованный','C1','technology'),
('latency','задержка','C1','technology'),
('scalability','масштабируемость','C1','technology'),
('throughput','пропускная способность (ИТ)','C1','technology'),
('acumen','проницательность','C1','work'),
('adjudicate','выносить решение','C1','work'),
('efficacious','эффективный','C1','work'),
('incumbent','обязательный','C1','work'),
('meritocracy','меритократия','C1','work'),
('remuneration','вознаграждение','C1','work'),
('stipulate','оговаривать','C1','work'),
('abstruse','малопонятный','C1',NULL),
('acrimony','язвительность','C1',NULL),
('ameliorate','улучшать','C1',NULL),
('antithesis','антитезис','C1',NULL),
('arduous','трудный','C1',NULL),
('circumvent','обходить','C1',NULL),
('coalesce','объединяться','C1',NULL),
('cogent','убедительный','C1',NULL),
('commensurate','соразмерный','C1',NULL),
('corroborate','подтверждать','C1',NULL),
('eloquent','красноречивый','C1',NULL),
('equivocal','двусмысленный','C1',NULL),
('exacerbate','обострять','C1',NULL),
('heuristic','эвристический','C1',NULL),
('meticulous','тщательный','C1',NULL),
('paradigm','парадигма','C1',NULL),
('predominantly','преимущественно','C1',NULL),
('superfluous','излишний','C1',NULL),
('tenacious','настойчивый','C1',NULL),
('ubiquitous','повсеместный','C1',NULL),
('venerate','почитать','C1',NULL),
('alacrity','живость','C1',NULL),
('candid','откровенный','C1',NULL),
('dearth','нехватка','C1',NULL),
('ephemeral','эфемерный','C1',NULL),
('furtive','украдчивый','C1',NULL),
('garrulous','болтливый','C1',NULL),
('hapless','несчастный','C1',NULL),
('inveterate','закоренелый','C1',NULL),
('laconic','лаконичный','C1',NULL),
('malevolent','злобный','C1',NULL),
('nascent','зарождающийся','C1',NULL),
('obstinate','упрямый','C1',NULL),
('propound','выдвигать (теорию)','C1',NULL),
('banal','банальный','C1',NULL),
('etiology','этиология','C1',NULL),
('commodification','товаризация','C1',NULL),
('deterministic','детерминированный','C1',NULL)
ON CONFLICT (english) DO NOTHING;

-- ============================================================
-- C2 — Proficiency (100 words)
-- ============================================================
INSERT INTO words (english, russian, level, category) VALUES
('gustatory','вкусовой','C2','food'),
('oleaginous','маслянистый','C2','food'),
('comestible','съедобный','C2','food'),
('alimentary','пищевой','C2','food'),
('inspissate','сгущать','C2','food'),
('deglutition','глотание','C2','food'),
('circumnavigate','огибать земной шар','C2','travel'),
('peregrinate','странствовать','C2','travel'),
('wanderlust','страсть к путешествиям','C2','travel'),
('solivagant','любящий одиночные путешествия','C2','travel'),
('tramontane','заальпийский','C2','travel'),
('fenestration','расположение окон','C2','home'),
('inglenook','каминный угол','C2','home'),
('loggia','лоджия','C2','home'),
('crepuscular','сумеречный','C2','home'),
('escarpment','откос','C2','home'),
('abstemious','умеренный','C2','health'),
('anamnesis','анамнез','C2','health'),
('cachexia','кахексия','C2','health'),
('febrifuge','жаропонижающее','C2','health'),
('nosocomial','внутрибольничный','C2','health'),
('sequela','последствие болезни','C2','health'),
('epistemology','эпистемология','C2','education'),
('hermeneutics','герменевтика','C2','education'),
('dialectic','диалектика','C2','education'),
('exegesis','экзегеза','C2','education'),
('apophthegm','изречение','C2','education'),
('petrichor','запах дождя','C2','nature'),
('sidereal','звёздный','C2','nature'),
('lacustrine','озёрный','C2','nature'),
('lithosphere','литосфера','C2','nature'),
('abscission','опадение листьев','C2','nature'),
('anaerobic','анаэробный','C2','nature'),
('xerophyte','ксерофит','C2','nature'),
('arbitrage','арбитраж','C2','shopping'),
('escrow','эскроу','C2','shopping'),
('fungibility','взаимозаменяемость','C2','shopping'),
('monopsony','монопсония','C2','shopping'),
('usufruct','узуфрукт','C2','shopping'),
('anachronism','анахронизм','C2','entertainment'),
('bathos','батос','C2','entertainment'),
('bricolage','бриколаж','C2','entertainment'),
('diegesis','диегезис','C2','entertainment'),
('ekphrasis','экфрасис','C2','entertainment'),
('legerdemain','ловкость рук','C2','entertainment'),
('palimpsest','палимпсест','C2','entertainment'),
('obfuscation','запутывание','C2','technology'),
('ontology','онтология (ИТ)','C2','technology'),
('stochastic','стохастический','C2','technology'),
('telemetry','телеметрия','C2','technology'),
('isomorphism','изоморфизм','C2','technology'),
('heuristics','эвристика','C2','technology'),
('malfeasance','должностное преступление','C2','work'),
('misfeasance','злоупотребление должностью','C2','work'),
('nonfeasance','бездействие (юр.)','C2','work'),
('approbation','одобрение','C2','work'),
('exculpate','оправдывать','C2','work'),
('anomie','аномия','C2','work'),
('abeyance','временное прекращение','C2',NULL),
('accretion','нарастание','C2',NULL),
('adumbrate','набрасывать','C2',NULL),
('anfractuous','извилистый','C2',NULL),
('apocryphal','апокрифический','C2',NULL),
('assiduous','усердный','C2',NULL),
('cerulean','лазурный','C2',NULL),
('chiaroscuro','светотень','C2',NULL),
('contemn','презирать','C2',NULL),
('evanescent','мимолётный','C2',NULL),
('execrable','отвратительный','C2',NULL),
('fugacious','скоротечный','C2',NULL),
('ineffable','невыразимый','C2',NULL),
('juxtaposition','сопоставление','C2',NULL),
('loquacious','говорливый','C2',NULL),
('mellifluous','медоточивый','C2',NULL),
('mendacious','лживый','C2',NULL),
('numinous','священный','C2',NULL),
('obstreperous','шумный','C2',NULL),
('perspicacious','проницательный','C2',NULL),
('quintessential','квинтэссенциальный','C2',NULL),
('recondite','малоизвестный','C2',NULL),
('sagacious','мудрый','C2',NULL),
('serendipity','счастливый случай','C2',NULL),
('solipsism','солипсизм','C2',NULL),
('surreptitious','тайный','C2',NULL),
('pulchritudinous','красивый (кн.)','C2',NULL),
('hiraeth','тоска по родине','C2',NULL),
('vellichor','странная грусть','C2',NULL),
('lacto-fermentation','лактоферментация','C2','food'),
('peripeteia','перипетия','C2','travel'),
('lissome','гибкий','C2','home'),
('aetiology','этиология (брит.)','C2','health'),
('maieutic','майевтический','C2','education'),
('propaedeutic','пропедевтический','C2','education'),
('crepitate','потрескивать','C2','nature'),
('incumbrance','обременение','C2','shopping'),
('apotheosis','апофеоз','C2','technology'),
('analepsis','ретроспекция','C2','work'),
('cachinnate','громко смеяться','C2',NULL)
ON CONFLICT (english) DO NOTHING;

-- Update words_count in word_categories
UPDATE word_categories wc
SET words_count = (
    SELECT COUNT(*) FROM words w WHERE w.category = wc.code
)
WHERE EXISTS (SELECT 1 FROM words w WHERE w.category = wc.code);
